### ISSUE TITLE
Can I find the log file of creat-react-app project?

### ISSUE THREAD

**Issue by 2071534594** [arcanis/pnp-webpack-plugin#11]
**Is this a bug report?**
No
[pictue of init project](https://user-images.githubusercontent.com/45158066/56637783-120a2a00-669f-11e9-9ff5-b4055c3b8250.jpg)

**what i want?**
I want to know where is the log about init the project.
I have set the global cache,but i don't find the log about "npx  creat-react-app test" in
node_cache _log folder,where can i find it or it is not exit?

**Comment by arcanis** [comment]
That's not an issue about this plugin, is it...?
