### ISSUE TITLE
pnp is not defined

### ISSUE THREAD

**Issue by kirill-konshin** [arcanis/pnp-webpack-plugin#21]
https://github.com/arcanis/pnp-webpack-plugin/blob/master/index.js#L157
https://github.com/arcanis/pnp-webpack-plugin/blob/master/index.js#L162

Should probably be `process.versions.pnp`.

**Comment by arcanis** [comment]
Should be fixed in 1.6.4

**Comment by kirill-konshin** [comment]
Do you have an ETA when it will be released? Do you need any help with this?

**Comment by kirill-konshin** [comment]
Fix confirmed.
